[package]
name = "zFFI"
version = "0.1.0"
edition = "2021"
license = "Unlicense"
license-file = "LICENSE"
readme = "README.md"
authors = ["Matheus Catarino <matheus-catarino@hotmail.com>"]
keywords = ["ffi", "rust", "zig"]
# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cbindgen = {git = "https://github.com/kassane/cbindgen", branch = "zig-bindgen" }
