name: CI

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: build
        run: zig build cargo && zig build run
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: goto-bus-stop/setup-zig@v1
        with:
          version: master
      - run: rm -fr zig-cache && cargo fmt -- --check && zig fmt --check --ast-check */*.zig
